# Generated by Django 5.1.2 on 2024-10-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultycoordinator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentcoordinator',
            name='id',
        ),
        migrations.AlterField(
            model_name='facultycoordinator',
            name='coordinator_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentcoordinator',
            name='coordinator_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
