# Generated by Django 5.1.4 on 2024-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0001_initial'),
        ('podcast', '0002_podcast_description_podcast_hosts_podcast_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='hosted_podcasts', to='alumni_details.student'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='spoken_podcasts', to='alumni_details.alumni'),
        ),
    ]
