# Generated by Django 5.1.3 on 2024-12-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_video_uploaded_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Podcast',
        ),
    ]
