"""
Django settings for Nexus project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('THE_SECRETE_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


'''For production'''
# DEBUG = config('MY_DEBUG', cast=bool)


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'alumni_details',
    'achievements',
    'podcast',
    
    'coordinators',
    'events_cec',

    
    
    'image_uploader_widget', #custom image uploader
    'widget_tweaks', #this is added to put css for update-profile html page
    'login_history', #To track the user login
    # 'django_admin_logs', #To track super user login
  


]

# Allows the superuser to delete the admin logs(True)

# DJANGO_ADMIN_LOGS_DELETABLE = True

# This allows super users, or any staff users with the delete_logentry permission, to delete log entries from within the admin interface.

# DJANGO_ADMIN_LOGS_ENABLED = True  #set false if u dont want

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]

ROOT_URLCONF = 'Nexus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nexus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

import os
STATIC_URL = 'static/'


MEDIA_URL ='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


'''Login'''
# LOGIN_URL = 'alumni_login'
# LOGIN_REDIRECT_URL = 'alumni_home'
# LOGOUT_REDIRECT_URL = 'alumni_login'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






''' Admin pannel '''


JAZZMIN_SETTINGS = {
    "site_title": "Alumni Connect",
    "site_header": "Welcome To Alumni Portal",
    "site_brand": "Nexus",
    "site_icon": "images/favicon.png",
    # Add your own branding here
    "site_logo": "alumni_details/assets/Nexus_logo-removebg-preview.png",
    "welcome_sign": "Welcome to the your_site_name",
    # Copyright on the footer
    "copyright": "Nexus-alumni-portal @ 2024",
    "user_avatar": "alumni_details/assets/Nexus_logo-removebg-preview.png",
}