# Generated by Django 5.1.3 on 2024-12-15 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events_cec', '0006_alter_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('profile_view_student', 'Profile View by Student'), ('profile_view_alumni', 'Profile View by Alumni'), ('upcoming_event', 'Upcoming Event'), ('system', 'System Notification')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('viewer_photo', models.URLField(blank=True, max_length=1000, null=True)),
                ('viewer_profile_url', models.CharField(blank=True, max_length=500, null=True)),
                ('viewer_type', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], max_length=10, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events_cec.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
