# Generated by Django 5.1.3 on 2024-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_group',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('alumni', 'Alumni Only'), ('specific', 'Specific Users')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('profile_view_student', 'Profile View by Student'), ('profile_view_alumni', 'Profile View by Alumni'), ('upcoming_event', 'Upcoming Event'), ('system', 'System Notification'), ('targeted', 'Targeted Notification')], max_length=25),
        ),
    ]
