# Generated by Django 5.1.2 on 2024-10-25 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumni_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('graduation_year', models.IntegerField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default.png', null=True, upload_to='photos/')),
                ('batch', models.CharField(max_length=10)),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('current_position', models.CharField(db_index=True, max_length=255, null=True)),
                ('branch', models.CharField(db_index=True, max_length=100)),
                ('company_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('is_alumni', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['first_name'], name='alumni_deta_first_n_20db9f_idx'), models.Index(fields=['last_name'], name='alumni_deta_last_na_97b55d_idx'), models.Index(fields=['current_position'], name='alumni_deta_current_b496d1_idx'), models.Index(fields=['graduation_year'], name='alumni_deta_graduat_3b3cfb_idx'), models.Index(fields=['branch'], name='alumni_deta_branch_b20b3a_idx'), models.Index(fields=['company_name'], name='alumni_deta_company_65d7cb_idx')],
            },
        ),
    ]
