# Generated by Django 5.1.4 on 2024-12-24 18:36

import alumni_details.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumni_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('graduation_year', models.IntegerField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/', validators=[alumni_details.models.validate_image_size])),
                ('batch', models.CharField(max_length=10)),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=255, null=True)),
                ('current_position', models.CharField(db_index=True, max_length=255, null=True)),
                ('branch', models.CharField(db_index=True, max_length=100)),
                ('company_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('is_alumni', models.BooleanField(default=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('profile_views', models.IntegerField(default=alumni_details.models.generate_random_views)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memories/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='alumni_details.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('count_mem_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Joint Secretary', 'Joint Secretary')], max_length=20)),
                ('year', models.IntegerField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_members', to='alumni_details.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['first_name'], name='alumni_deta_first_n_20db9f_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['last_name'], name='alumni_deta_last_na_97b55d_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['current_position'], name='alumni_deta_current_b496d1_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['graduation_year'], name='alumni_deta_graduat_3b3cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['branch'], name='alumni_deta_branch_b20b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['company_name'], name='alumni_deta_company_65d7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['job_location'], name='alumni_deta_job_loc_e60621_idx'),
        ),
        migrations.AddIndex(
            model_name='councilmember',
            index=models.Index(fields=['role'], name='alumni_deta_role_36630f_idx'),
        ),
        migrations.AddIndex(
            model_name='councilmember',
            index=models.Index(fields=['year'], name='alumni_deta_year_1d8f3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='councilmember',
            unique_together={('alumni', 'role', 'year')},
        ),
    ]
