# Generated by Django 5.1.2 on 2024-10-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
