# Generated by Django 5.1.2 on 2024-10-31 05:25

import alumni_details.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0004_councilmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_picture',
            field=models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/', validators=[alumni_details.models.validate_image_size]),
        ),
    ]
