# Generated by Django 5.1.3 on 2024-11-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0005_alter_alumni_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memories/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='alumni_details.alumni')),
            ],
        ),
    ]
