# Generated by Django 5.1.3 on 2024-12-14 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0006_alumnimemory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='job_location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['job_location'], name='alumni_deta_job_loc_e60621_idx'),
        ),
    ]
