# Generated by Django 5.1.3 on 2024-12-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0007_alumni_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
