# Generated by Django 5.1.3 on 2024-12-24 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0008_alumni_facebook_url_alumni_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
