# Generated by Django 5.1.3 on 2024-12-24 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0010_generate_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='profile_views',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
