# Generated by Django 5.1.3 on 2024-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0016_alter_alumni_profile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_views',
            field=models.IntegerField(default=4),
        ),
    ]
