# Generated by Django 5.1.3 on 2024-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_details', '0019_alter_alumni_profile_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='profile_views',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.IntegerField(db_index=True),
        ),
    ]
