# Generated by Django 5.1.4 on 2024-12-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('internship', 'Internship Offer'), ('job', 'Job Offer'), ('workshop', 'Workshop'), ('others', 'Others')], max_length=50)),
                ('details', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
            ],
        ),
    ]
