# Generated by Django 5.1.2 on 2024-10-31 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='event_title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='events_cec.event')),
            ],
        ),
    ]
