# Generated by Django 5.1.4 on 2025-01-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0002_socialmediaimages_socialmediaposts_socialmediareels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediareels',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
