# Generated by Django 5.1.3 on 2024-12-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0002_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_uploaded',
            field=models.DateTimeField(),
        ),
    ]
