# Generated by Django 5.1.3 on 2024-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0003_alter_gallery_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
