# Generated by Django 5.1.4 on 2025-01-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0003_alter_socialmediareels_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediareels',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='socialmediareels',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
