# Generated by Django 5.1.4 on 2025-01-18 09:13

import events_cec.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0004_alter_socialmediareels_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/', validators=[events_cec.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='socialmediaimages',
            name='images',
            field=models.ImageField(upload_to='SocialMediaImages/', validators=[events_cec.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='socialmediaposts',
            name='image',
            field=models.ImageField(upload_to='SocialMediaPosts/', validators=[events_cec.models.validate_image_size]),
        ),
    ]
