# Generated by Django 5.1.3 on 2024-12-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0004_gallery_date_alter_gallery_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('event', 'Event'), ('others', 'Others')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
