# Generated by Django 5.1.3 on 2024-12-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0005_event_category_event_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('talk', 'Alumni Talk'), ('others', 'Others')], max_length=50),
        ),
    ]
