# Generated by Django 5.1.4 on 2025-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cec', '0005_alter_event_poster_alter_socialmediaimages_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast', models.IntegerField()),
                ('events', models.IntegerField()),
                ('workshops', models.IntegerField()),
                ('interactions', models.IntegerField()),
            ],
        ),
    ]
